FROM python:3.13.5-alpine3.22@sha256:37b14db89f587f9eaa890e4a442a3fe55db452b69cca1403cc730bd0fbdc8aaf

RUN addgroup -S -g 10001 archive \
 && adduser -S -D -H -u 10001 -G archive archive \
 && mkdir -p /var/cache/blob-archive \
 && chown archive:archive /var/cache/blob-archive

COPY --chown=archive:archive blob-archive-proxy.py /app/blob-archive-proxy.py

USER archive
EXPOSE 3500
ENTRYPOINT ["python3", "/app/blob-archive-proxy.py"]
