import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Explicit sidebar (not autogenerated) so the reading order and category
// grouping are intentional rather than alphabetical.
const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      items: ['getting-started', 'architecture', 'fees', 'comparison'],
    },
    {
      type: 'category',
      label: 'Build with Ophis',
      collapsed: false,
      items: ['intent-api', 'ai-agents'],
    },
    {
      type: 'category',
      label: 'Trust',
      collapsed: false,
      items: ['audits', 'status', 'faq'],
    },
  ],
};

export default sidebars;
