node-url = "https://ethereum-sepolia.publicnode.com"
simulation-node-url = "https://ethereum-sepolia.publicnode.com"

[logging]
filter = "warn,autopilot=debug,shared=info,price_estimation=info"

[current-block]
poll-interval = "1s"

[run-loop]
solve-deadline = "20s"

[[gas-estimators]]
type = "Web3"

[[gas-estimators]]
type = "Alloy"

[[drivers]]
name = "baseline"
url = "http://driver/baseline"
address = "0x92B9bE5e96795E8630fDC61efb0e705E75b1A1B1"

[fee-policies]

[database]
write-url = "%DB_WRITE_URL"
read-url = "%DB_READ_URL"

[ethflow]
contracts = ["0x0b7795E18767259CC253a2dF471db34c72B49516"]
skip-event-sync = true

[order-quoting]
price-estimation-drivers = [{ name = "baseline", url = "http://driver/baseline" }]

[native-price-estimation]
estimators = [[{ type = "Driver", name = "baseline", url = "http://driver/baseline" }]]

[native-price-estimation.cache]
max-age = "20m"
