// Disposable keys only. No network, live signer, or production configuration access.
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { createHash } = require('node:crypto')
const { readSolver, prepare } = require('./solver.cjs')
const { root } = require('./plan.cjs')
const example = JSON.parse(fs.readFileSync(path.join(__dirname, 'config.example.json')))
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'arc-solver-check-'))
const key = path.join(dir, 'arc.key'), output = path.join(dir, 'config.json')
const hash = file => createHash('sha256').update(fs.readFileSync(file)).digest('hex')
try {
  fs.chmodSync(dir, 0o700)
  assert.throws(() => prepare(example, output, key, NaN, true), /nonce/)
  assert(!fs.existsSync(key))
  fs.chmodSync(dir, 0o755)
  assert.throws(() => prepare(example, output, key, 12, true), /0700/)
  fs.chmodSync(dir, 0o700)
  const prepared = prepare(example, output, key, 12, true)
  const signer = readSolver(key), original = hash(key)
  assert.equal(prepared.solver, signer.address)
  assert.equal(prepared.nonce, 12)
  assert.equal(fs.statSync(key).mode & 0o777, 0o600)
  assert.equal(fs.statSync(output).mode & 0o777, 0o600)
  assert(!fs.readFileSync(output, 'utf8').includes(fs.readFileSync(key, 'utf8').trim()))
  assert.throws(() => prepare(example, output, key, 13, true), /already exists/)
  assert.throws(() => prepare(example, output + '.new', key, 13, true), /EEXIST/)
  assert.equal(hash(key), original, 'Repeated preparation changed the key')
  assert.equal(JSON.parse(fs.readFileSync(output)).nonce, 12)
  assert.equal(prepare(example, output + '.reuse', key, 13).solver, signer.address)
  assert.throws(() => prepare({ ...example, solver: example.deployer }, output + '.wrong', key, 13), /differs from key/)
  assert(!fs.existsSync(output + '.wrong'))
  assert.throws(() => prepare({ ...example, safeOwners: [signer.address, ...example.safeOwners.slice(1)] }, output + '.owner', key, 13), /governance signers/)
  fs.chmodSync(key, 0o644)
  assert.throws(() => readSolver(key), /0600/)
  fs.chmodSync(key, 0o600)
  fs.symlinkSync(key, key + '.link')
  assert.throws(() => readSolver(key + '.link'))
  assert.throws(() => readSolver(dir), /regular file/)
  assert.throws(() => readSolver(path.join(root, 'repo.key')), /outside the checkout/)
  fs.writeFileSync(key + '.invalid', 'not a private key', { mode: 0o600 })
  assert.throws(() => readSolver(key + '.invalid'), /Invalid solver key file format/)
  fs.writeFileSync(key + '.invalid', '0'.repeat(64))
  assert.throws(() => readSolver(key + '.invalid'), /^Error: Invalid solver key$/)
  fs.writeFileSync(key + '.invalid', 'a'.repeat(129))
  assert.throws(() => readSolver(key + '.invalid'), /regular file/)
  console.log('PASS Arc key creation, identity binding, governance separation, private files, overwrite/symlink/malformed-key rejection; zero RPC calls')
} finally { fs.rmSync(dir, { recursive: true, force: true }) }
