node-url = "https://sepolia.optimism.io"
simulation-node-url = "https://sepolia.optimism.io"

[contracts]
settlement = "0x0864b65F1EFe752a699d119Ae0419E7331a8Bfce"
balances = "0x13f618796e8c8626168340558453ebda02add1ff"
signatures = "0x764fe4aa1ff493cf39931c7923c8ff5837596504"
native-token = "0x4200000000000000000000000000000000000006"
hooks = "0xe4137bd2ecfdfb96d80629ec254dadec71bc498c"
balancer-v2-vault = "0xBA12222222228d8Ba445958a75a0704d566BF2C8"

[logging]
filter = "warn,autopilot=debug,shared=info,price_estimation=info"

[current-block]
poll-interval = "2s"  # OP block time

[run-loop]
solve-deadline = "20s"

[[gas-estimators]]
type = "Web3"

[[gas-estimators]]
type = "Alloy"

[[drivers]]
name = "baseline"
url = "http://driver/baseline"
address = "0x00f98b5776eb0f6a8c0c925ddF51f9Ade8a1502F"

[fee-policies]

[database]
write-url = "%DB_WRITE_URL"
read-url = "%DB_READ_URL"

[order-quoting]
price-estimation-drivers = [{ name = "baseline", url = "http://driver/baseline" }]

[price-estimation]
amount-to-estimate-prices-with = "1000000000000000"

[native-price-estimation]
estimators = [[{ type = "Driver", name = "baseline", url = "http://driver/baseline" }]]

[native-price-estimation.cache]
max-age = "20m"
