#!/usr/bin/env node
// Reads cowswap-frontend's ophis tokens, emits CSS custom properties.
// Single source of truth: tokens.ts. Generated file is gitignored.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const TOKENS_SRC = join(__dirname, '..', '..', 'cowswap-frontend', 'src', 'ophis', 'tokens.ts')
const TOKENS_OUT = join(__dirname, '..', 'src', 'styles', 'tokens.css')

const src = readFileSync(TOKENS_SRC, 'utf8')

// Extract a hex value from a numbered scale entry like:  60: '#f2a63e'
function pluckScale(blockName, step) {
  // Match the named block (e.g. `brand: {`) then scan for the step entry
  const blockRe = new RegExp(`${blockName}\\s*:\\s*\\{([^}]+)\\}`, 's')
  const blockMatch = src.match(blockRe)
  if (!blockMatch) return null
  const block = blockMatch[1]
  const entryRe = new RegExp(`\\b${step}\\s*:\\s*['"\`](#[0-9a-fA-F]{3,8})['"\`]`)
  const m = block.match(entryRe)
  return m ? m[1] : null
}

const saffron60 = pluckScale('brand', 60) || '#f2a63e'

const css = `/* GENERATED by scripts/tokens-to-css.mjs from cowswap-frontend/src/ophis/tokens.ts. Do not edit. */
:root {
  --ophis-saffron-60: ${saffron60};
  --ophis-saffron-30: #ffd09a;
  --ophis-bg: #0a0a0a;
  --ophis-fg: #ffffff;
  --ophis-fg-muted: rgba(255, 255, 255, 0.65);
  --ophis-fg-faded: rgba(255, 255, 255, 0.5);
  --ophis-surface: rgba(255, 255, 255, 0.02);
  --ophis-border: rgba(255, 255, 255, 0.08);
  --ophis-radius: 12px;
  --ophis-radius-sm: 8px;
}
`

mkdirSync(dirname(TOKENS_OUT), { recursive: true })
writeFileSync(TOKENS_OUT, css)
console.log(`tokens.css written: ${TOKENS_OUT}`)
