#!/usr/bin/env node
// Emits the landing design tokens as CSS custom properties.
// Single source of truth: the approved Steep palette (paper white, ink,
// mist, blush peach, sienna brown). Generated file is gitignored.
//
// Names keep the historic --ophis-* prefix so every component, layout, and
// page keeps working unchanged; only the values moved from the old dark
// theme to Steep. --ophis-saffron-60 is the primary-action ink and
// --ophis-saffron-30 the warm accent (brown), per the Steep reference.

import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const TOKENS_OUT = join(__dirname, '..', 'src', 'styles', 'tokens.css')

const css = `/* GENERATED by scripts/tokens-to-css.mjs from the approved Steep palette. Do not edit. */
:root {
  --ophis-saffron-60: #17191c;
  --ophis-saffron-30: #5d2a1a;
  --ophis-bg: #ffffff;
  --ophis-fg: #17191c;
  --ophis-fg-muted: #5b5f68;
  --ophis-fg-faded: #6e737d;
  --ophis-surface: #f2f2f3;
  --ophis-border: #e8e8ea;
  --ophis-peach: #fbe1d1;
  --ophis-brown: #5d2a1a;
  --ophis-fog: #fafafb;
  --ophis-radius: 24px;
  --ophis-radius-sm: 8px;
}
`

mkdirSync(dirname(TOKENS_OUT), { recursive: true })
writeFileSync(TOKENS_OUT, css)
console.log(`tokens.css written: ${TOKENS_OUT}`)
