node-url = "https://rpc-bokuto.katanarpc.com"
simulation-node-url = "https://rpc-bokuto.katanarpc.com"

[contracts]
settlement = "0x0000000000000000000000000000000000000000"
balances = "0x0000000000000000000000000000000000000000"
signatures = "0x0000000000000000000000000000000000000000"
native-token = "0x4200000000000000000000000000000000000006"
hooks = "0x0000000000000000000000000000000000000000"
balancer-v2-vault = "0xBA12222222228d8Ba445958a75a0704d566BF2C8"

[logging]
filter = "warn,autopilot=debug,shared=info,price_estimation=info"

[current-block]
poll-interval = "1s"

[run-loop]
solve-deadline = "20s"

[[gas-estimators]]
type = "Web3"

[[gas-estimators]]
type = "Alloy"

[[drivers]]
name = "baseline"
url = "http://driver/baseline"
address = "0x00f98b5776eb0f6a8c0c925ddF51f9Ade8a1502F"

[fee-policies]

[database]
write-url = "%DB_WRITE_URL"
read-url = "%DB_READ_URL"

[order-quoting]
price-estimation-drivers = [{ name = "baseline", url = "http://driver/baseline" }]

[price-estimation]
amount-to-estimate-prices-with = "1000000000000000"

[native-price-estimation]
estimators = [[{ type = "Driver", name = "baseline", url = "http://driver/baseline" }]]

[native-price-estimation.cache]
max-age = "20m"
